# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def0a12a285c926ad4d91ec3ce1c71c6c1ea99c7583386b87f7c7c5afad0ead6be03d885e22df1bf54366b81dd034619ca7b4ea03337e45931e6b8971391002e

test:
  secret_key_base: f75456190e4ba3e82370cd0051e4041e66924a6bc1974cf7107bf2f41387799311c7689ad78d7cc964d911529ee5b403dea74133ab2cfe73a73f104921238ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
